# Copyright (C) 2021 The uOFW team
# See the file COPYING for copying permission.

TARGET = adhocctl
OBJS = pspnet_adhocctl.o

#DEBUG = 1

LIBS = -lsceUtility -lSysMemUserForUser -lscePower -lsceNetAdhocAuth_lib -lsceWlanDrv_lib -lsceWlanDrv -lsceNet -lsceNet_lib -lsceNetAdhoc -lsceReg -lKernel_Library -lModuleMgrForUser -lThreadManForUser

include ../../lib/build.mak
